login:
  path: /login
  defaults: { _controller: AppBundle:Default:Login }

login_check:
  path: /login_check

logout:
  path: /logout
  
Home:
  path: /Home
  defaults: {_controller: AppBundle:Default:DatosPersonales}

Listar_Alumnos:
  path: /Home/Alumnos/{page}
  defaults: {_controller: AppBundle:Default:ListarAlumnos,page: 1}

Listar_Ofertas:
  path: /Home/Ofertas/{page}
  defaults: {_controller: AppBundle:Default:ListarOfertas,page: 1}

Listar_MisOfertas:
  path: /Home/MisOfertas/{page}
  defaults: {_controller: AppBundle:Default:MisOfertas,page: 1}


