login:
  path: /login
  defaults: { _controller: AppBundle:Default:Login }

login_check:
  path: /login_check

logout:
  path: /logout

Home:
  path: /Home
  defaults: {_controller: AppBundle:Loged:Home}
#---------------------------------CRUD Ofertas--------------------------------

#---------------------------------CRUD Usuarios--------------------------------

#---------------------------------CRUD Titulaciones--------------------------------

#---------------------------------CRUD Grados--------------------------------



