login:
  path: /login
  defaults: { _controller: AppBundle:Default:Login }

login_check:
  path: /login_check

logout:
  path: /logout
  
Home:
  path: /Home
  defaults: {_controller: AppBundle:Default:DatosPersonales}

Alumno_Delete:
  path: /Alumnos/Delete
  defaults: { _controller: AppBundle:Default:Delete }

Modificar_Alumno:
  path: /Alumnos/Modificar
  defaults: { _controller: AppBundle:Default:ModificarAlumno }

Alumno_Confirmar:
  path: /Alumnos/Confirmar/{id}
  defaults: { _controller: AppBundle:Default:ConfirmarAlumno }

Listar_Alumnos:
  path: /Alumnos/{page}
  defaults: {_controller: AppBundle:Default:ListarAlumnos,page: 1}

EnviarOferta:
  path: /Oferta/Enviar
  defaults: {_controller: AppBundle:Default:EnviarOferta}

Oferta_Delete:
  path: /Oferta/Delete
  defaults: { _controller: AppBundle:Default:DeleteOferta }

ValidarOferta:
  path: /Oferta/Validar/{id}
  defaults: {_controller: AppBundle:Default:Validar}

Listar_Ofertas:
  path: /Ofertas/{page}
  defaults: {_controller: AppBundle:Default:ListarOfertas,page: 1}

Listar_MisOfertas:
  path: /MisOfertas/{page}
  defaults: {_controller: AppBundle:Default:MisOfertas,page: 1}

Grado_Delete:
  path: /Grados/Delete
  defaults: { _controller: AppBundle:Default:DeleteGrado }

Grado_Confirmar:
  path: /Grados/Confirmar/{id}
  defaults: { _controller: AppBundle:Default:ConfirmarGrado }

Listar_Grados:
  path: /Grados/{page}
  defaults: {_controller: AppBundle:Default:ListarGrados,page: 1}






